export const BUTTON_TYPES = {
  BRACKETS: "BRACKETS",
  OPEN_BRACKETS: "OPEN_BRACKETS",
  CLOSE_BRACKETS: "CLOSE_BRACKETS",
  PERCENTAGE: "PERCENTAGE",
  CE: "CE",
  DIVISION: "DIVISION",
  MULTIPLICATION: "MULTIPLICATION",
  REMOVE: "REMOVE",
  ADDITION: "ADDITION",
  CALCULATE: "CALCULATE",
  NUMBER: "NUMBER",
};
