export const CALCULATION_ITEM_TYPES = {
  BRACKETS: "BRACKETS",
  PERCENTAGE: "PERCENTAGE",
  CE: "CE",
  DIVISION: "DIVISION",
  MULTIPLICATION: "MULTIPLICATION",
  REMOVE: "REMOVE",
  ADDITION: "ADDITION",
  CALCULATE: "CALCULATE",
  NUMBER: "NUMBER",
};

export const CALCULATION_ITEM_TEXTS = {
  OPEN_BRACKETS: "(",
  CLOSE_BRACKETS: ")",
  PERCENTAGE: "%",
  MULTIPLICATION: "x",
  DIVISION: "÷",
  REMOVE: "-",
  CALCULATE: "=",
  ADDITION: "+",
  CE: "CE",
  POINT: ".",
  ZERO: "0",
  ONE: "1",
  TWO: "2",
  THREE: "3",
  FOUR: "4",
  FIVE: "5",
  SIX: "6",
  SEVEN: "7",
  EIGHT: "8",
  NINE: "9",
};

export const CALCULATION_ITEM_CUSTOM_ACTIONS = {
  CE: "CE",
  CALCULATE: "CALCULATE",
  NUMBER: "NUMBER",
  OPEN_BRACKETS: "OPEN_BRACKETS",
  CLOSE_BRACKETS: "CLOSE_BRACKETS",
};
